#!/usr/bin/env node

const child_process = require("child_process");

// adb shell dumpsys window
main(1080, 2400, +process.argv[2]);

async function main(width, height, times = 1) {
  for (let i = 0, ii = times || 1; i < ii; i++) {
    await swipeRandom(
      width / 4,
      height / 2,
      (3 * width) / 4,
      height / 2,
      width / 8,
    );

    await sleep(randomBetween(20, 50));
  }
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function swipeRandom(fx, fy, tx, ty, r) {
  const from = randomPoint(fx, fy, r, r);
  const to = randomPoint(tx, ty, r, r);
  return swipeExact(from.x, from.y, to.x, to.y);
}

function swipeExact(fx, fy, tx, ty) {
  return adb("shell", "input", "swipe", fx, fy, tx, ty);
}

function adb(...args) {
  return new Promise((resolve, reject) => {
    const proc = child_process.spawn("adb", args, {
      stdio: "inherit",
    });

    proc.on("data", (data) => process.stdout.write(data));
    proc.on("error", reject);
    proc.on("exit", (code) => (code ? reject(code) : resolve()));
  });
}

function randomPoint(cx, cy, hw, hh) {
  return {
    x: randomBetween(cx - hw, cx + hw),
    y: randomBetween(cy - hh, cy + hh),
  };
}

function randomBetween(min, max) {
  return Math.floor(min + Math.random() * (max - min));
}
